FROM almalinux:9
ENV container docker
# Install systemd and clean up
RUN dnf install -y systemd systemd-libs && \
    dnf clean all && \
    rm -rf /var/cache/dnf/* /tmp/* /var/tmp/*
# Systemd requires this to identify the machine
RUN touch /etc/machine-id
# Set the entrypoint to systemd
STOPSIGNAL SIGRTMIN+3
CMD ["/usr/lib/systemd/systemd"]
